In [1]:
from keras.preprocessing import sequence  
from keras.models import Sequential  
from keras.datasets import boston_housing  
from keras.layers import Dense, Dropout 
# from keras.utils import multi_gpu_model  
# from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
from keras import regularizers  # 正则化  
import matplotlib.pyplot as plt  
import numpy as np
from sklearn.preprocessing import MinMaxScaler  
import pandas as pd

In [ ]:
# 时间点长度
time_stamp = 50
input_stamp = 2

# 划分训练集与验证集
google_stock = google_stock[['Open', 'High', 'Low', 'Close', 'Volume']]  #  'Volume'
train = google_stock[0:2800 + time_stamp]
valid = google_stock[2800 - time_stamp:]

# 归一化
scaler = MinMaxScaler(feature_range=(0, 1))  
scaled_data = scaler.fit_transform(train)
print(scaled_data.shape)
print(scaled_data[1, 3])

# 训练集
x_train, y_train = [], []
for i in range(time_stamp, len(train)-input_stamp+1):
    x_train.append(scaled_data[i - time_stamp:i])
#     y_train.append(scaled_data[i, 3])
    y_train.append(scaled_data[i:i+input_stamp, 3])
x_train, y_train = np.array(x_train), np.array(y_train)

# 验证集
scaled_data = scaler.fit_transform(valid)
x_valid, y_valid = [], []
for i in range(time_stamp, len(valid)-input_stamp+1):
    x_valid.append(scaled_data[i - time_stamp:i])
#     y_valid.append(scaled_data[i, 3])
    y_valid.append(scaled_data[i:i+input_stamp, 3])
x_valid, y_valid = np.array(x_valid), np.array(y_valid)

print(x_train.shape)
print(x_valid.shape)
print(y_train.shape)
print(y_valid.shape)
train.head()

In [14]:
data = pd.read_csv(r"./siping_4g.csv")
data = data.fillna(-1)  # Nan值填充
data = shuffle(data)
data
# 划分训练集与验证集
train, valid = 
x_train, x_valid, y_train, y_valid = train_test_split(samples, labels, test_size=0.2)

TrajID          IMEI          IMSI        MRTime   Longitude   Latitude  \
2314       9  8.623050e+14  4.600910e+14  1.521796e+12  121.496691  31.286612   
2656      12  8.625340e+14  4.600916e+14  1.559724e+12  121.495688  31.283307   
66         0  8.623050e+14  4.600910e+14  1.521793e+12  121.496059  31.282945   
366        0  8.623050e+14  4.600910e+14  1.521793e+12  121.496071  31.282949   
1846       5  8.623050e+14  4.600910e+14  1.521795e+12  121.495209  31.285153   
...      ...           ...           ...           ...         ...        ...   
2465      10  8.623050e+14  4.600910e+14  1.521796e+12  121.495468  31.286208   
2757      13  8.625340e+14  4.600916e+14  1.559729e+12  121.502642  31.284689   
854        0  8.623050e+14  4.600910e+14  1.521793e+12  121.493493  31.286288   
2582      11  8.623050e+14  4.600910e+14  1.521796e+12  121.495260  31.284902   
2463      10  8.623050e+14  4.600910e+14  1.521796e+12  121.495468  31.286208   

      Altitude  Accuracy     Speed  Dbm  ...  Unnamed: 121  Unnamed: 122  \
2314      56.0       9.0  2.030000 -111  ...          -1.0          -1.0   
2656      39.0      19.0  0.000000 -109  ...          -1.0          -1.0   
66        47.0       5.0  0.000000 -109  ...          -1.0          -1.0   
366       45.0      10.0  0.000000 -109  ...          -1.0          -1.0   
1846      31.0      35.0  0.000000 -109  ...          -1.0          -1.0   
...        ...       ...       ...  ...  ...           ...           ...   
2465       8.0       8.0  1.994242 -109  ...          -1.0          -1.0   
2757      73.0      76.0  1.332404 -109  ...          -1.0          -1.0   
854       30.0       9.0  0.000000 -109  ...          -1.0          -1.0   
2582      21.0      13.0  2.080096 -109  ...          -1.0          -1.0   
2463       8.0       8.0  1.994242 -109  ...          -1.0          -1.0   

      Unnamed: 123  Unnamed: 124  Unnamed: 125  Unnamed: 126  Unnamed: 127  \
2314          -1.0          -1.0          -1.0          -1.0          -1.0   
2656          -1.0          -1.0          -1.0          -1.0          -1.0   
66            -1.0          -1.0          -1.0          -1.0          -1.0   
366           -1.0          -1.0          -1.0          -1.0          -1.0   
1846          -1.0          -1.0          -1.0          -1.0          -1.0   
...            ...           ...           ...           ...           ...   
2465          -1.0          -1.0          -1.0          -1.0          -1.0   
2757          -1.0          -1.0          -1.0          -1.0          -1.0   
854           -1.0          -1.0          -1.0          -1.0          -1.0   
2582          -1.0          -1.0          -1.0          -1.0          -1.0   
2463          -1.0          -1.0          -1.0          -1.0          -1.0   

      Unnamed: 128  Unnamed: 129  Unnamed: 130  
2314          -1.0          -1.0            -1  
2656          -1.0          -1.0            -1  
66            -1.0          -1.0            -1  
366           -1.0          -1.0            -1  
1846          -1.0          -1.0            -1  
...            ...           ...           ...  
2465          -1.0          -1.0            -1  
2757          -1.0          -1.0            -1  
854           -1.0          -1.0            -1  
2582          -1.0          -1.0            -1  
2463          -1.0          -1.0            -1  

[3479 rows x 131 columns]

In [ ]:
data = pd.read_csv(r"./siping_4g.csv")
data = data.fillna(-1)  # Nan值填充
#     print(data.iloc[1000])
if shuff:   # 将数据集打乱
    data = shuffle(data)
#     print(data.iloc[1000])
# 构建数据集和标签
samples = []
labels = []
for index, row in data.iterrows():
# print(row) # 输出每行的索引值
    matrix = []  # 7 * 4
    for i in range(7):
        matrix.append([i+1,
                       row['AsuLevel_' + str(i+1)],
                       row['SignalLevel_' + str(i+1)],
                       row['Dbm_' + str(i+1)]]) # 新数据集中不存在RSSI，使用Dbm(代功率的绝对值)
    # print(matrix)
    samples.append(matrix)
    labels.append([row['Longitude'], row['Latitude']])

In [15]:
from sklearn.utils import shuffle  

# 加载数据集
def load_data(data_path, shuff=True):
    data = pd.read_csv(data_path)
    data = data.fillna(-1)  # Nan值填充
#     print(data.iloc[1000])
    if shuff:   # 将数据集打乱
        data = shuffle(data)
#     print(data.iloc[1000])
    # 构建数据集和标签
    samples = []
    labels = []
    for index, row in data.iterrows():
    # print(row) # 输出每行的索引值
        matrix = []  # 7 * 4
        for i in range(7):
            matrix.append([i+1,
                           row['AsuLevel_' + str(i+1)],
                           row['SignalLevel_' + str(i+1)],
                           row['Dbm_' + str(i+1)]]) # 新数据集中不存在RSSI，使用Dbm(代功率的绝对值)
        # print(matrix)
        samples.append(matrix)
        labels.append([row['Longitude'], row['Latitude']])
    return np.array(samples), np.array(labels)

In [16]:
path = r"./siping_4g.csv"
samples, labels = load_data(path)
print(samples[0], labels[0])

[[  1.  66.   4. -74.]
 [  2.  56.   4. -84.]
 [  3.  55.   4. -85.]
 [  4.  52.   4. -88.]
 [  5.  -1.  -1.  -1.]
 [  6.  -1.  -1.  -1.]
 [  7.  -1.  -1.  -1.]] [121.4960593   31.28294483]


In [17]:
from sklearn.model_selection import train_test_split

# 划分数据集
x_train, x_valid, y_train, y_valid = train_test_split(samples, labels, test_size=0.2)  #划分训练数据、训练标签、验证数据、验证标签

print(x_train.shape)
print(x_valid.shape)
print(y_train.shape)
print(y_valid.shape)

(2783, 7, 4)
(696, 7, 4)
(2783, 2)
(696, 2)


In [11]:
# 训练集归一化  
min_max_scaler = MinMaxScaler()  
min_max_scaler.fit(x_train)  
x_train = min_max_scaler.transform(x_train)  

min_max_scaler.fit(y_train)  
y_train = min_max_scaler.transform(y_train)  
  
# 验证集归一化  
min_max_scaler.fit(x_valid)  
x_valid = min_max_scaler.transform(x_valid)  

min_max_scaler.fit(y_valid)  
y_valid = min_max_scaler.transform(y_valid)
x_train=x_train.reshape(-1,7,4)
y_train=y_train.reshape(-1,2)
x_valid=x_valid.reshape(-1,7,4)
y_valid=y_valid.reshape(-1,2)

ValueError: Found array with dim 3. MinMaxScaler expected <= 2.

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_valid.shape)
print(y_valid.shape)